blank_issues_enabled: false
contact_links:
  - name: Multi-Omics Metadata Standards Integration Working Group (MOMSI WG) 
    url: https://www.rd-alliance.org/groups/multi-omics-metadata-standards-integration-momsi-wg
    about: Background, context and objectives for the working group.
