name: Process order
on:
    issues:
        types: [labeled]
concurrency: 'main'

jobs:
    validation:
        runs-on: ubuntu-latest
        outputs:
            authorised-actor: ${{ steps.authorised-actor-check.outputs.valid && github.event.label.name == 'merge' }}
            has-pizza: ${{ contains(github.event.issue.labels, 'pizza') }}
            has-burger: ${{ contains(github.event.issue.labels, 'burger') }}
        steps:
            - name: Check if actor is authorised
              id: authorised-actor-check
              shell: bash
              run: |
                  if [ "${{ contains(fromJSON(secrets.AUTHORISED_MERGE), github.triggering_actor) }}" ]; then
                    echo "valid=true" >> $GITHUB_OUTPUT;
                  else
                    echo "valid=false" >> $GITHUB_OUTPUT;
                  fi
            - run: echo '${{ fromJSON(github.event.issue.labels) }}'
            - run: echo burger '${{ contains(github.event.issue.labels, 'burger') }}'
    pizzarisation:
        runs-on: ubuntu-latest
        needs: [validation]
        if: fromJSON(needs.validation.outputs.authorised-actor) && fromJSON(needs.validation.outputs.has-pizza)
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                node-version: '16'
            - uses: stefanbuck/github-issue-parser@v3
              id: issue-parser
              with:
                template-path: .github/ISSUE_TEMPLATE/order-pizza.yml

            - run: echo '${{ steps.issue-parser.outputs.jsonString }}' > order.json
            - run: cat order.json
            - run: node ./place-pizza-order.js

            - name: Commit changes
              shell: bash
              run: |
                  git config --global user.email "github-actions[bot]@users.noreply.github.com" && \
                  git config --global user.name "github-actions[bot]" && \
                  git add README.md && \
                  git commit -m 'Place order' && \
                  git push

            - name: Close Issue
              run: gh issue close --comment "Auto-closing issue" ${{ github.event.issue.number }}
              env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    burgerisation:
        runs-on: ubuntu-latest
        needs: [validation]
        if: fromJSON(needs.validation.outputs.authorised-actor) && fromJSON(needs.validation.outputs.has-burger)
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                node-version: '16'
            - uses: stefanbuck/github-issue-parser@v3
              id: issue-parser
              with:
                template-path: .github/ISSUE_TEMPLATE/order-burger.yml

            - run: echo '${{ steps.issue-parser.outputs.jsonString }}' > order.json
            - run: cat order.json
            - run: node ./place-burger-order.js

            - name: Commit changes
              shell: bash
              run: |
                  git config --global user.email "github-actions[bot]@users.noreply.github.com" && \
                  git config --global user.name "github-actions[bot]" && \
                  git add README.md && \
                  git commit -m 'Place order' && \
                  git push

            - name: Close Issue
              run: gh issue close --comment "Auto-closing issue" ${{ github.event.issue.number }}
              env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}