name: Process order
on:
  issues:
    types: [labeled]
concurrency: 'main'
env:
    AUTHORISED_ACTOR: ${{ contains(["turukawa",], github.triggering_actor) && github.event.label.name == 'merge' }}
jobs:
  setup:
    if: AUTHORISED_ACTOR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/order-pizza.yml

      - run: echo '${{ steps.issue-parser.outputs.jsonString }}' > order.json

      - run: cat order.json

      - run: node ./place-order.js

      - name: Commit changes
        shell: bash
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com" && \
          git config --global user.name "github-actions[bot]" && \
          git add README.md && \
          git commit -m 'Place order' && \
          git push

      - name: Close Issue
        run: gh issue close 